Algoritmo "1a100"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jaiion Costa dos Santos
// Descrição   : Soma dos numeros de 1 a 100
// Autor(a)    : Bruno Costa Prado
// Data atual  : 10/09/2021
Var
   // Seção de Declarações das variáveis
   num,cont:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para cont de 1 ate 100 passo 1 faca
   num<-num+cont
   Escreval(num)
   fimpara
Fimalgoritmo