Algoritmo "PARA4"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jaiion Costa dos Santos
// Descrição   : Ordem decrescente de 50 a 1
// Autor(a)    : Bruno Costa Prado
// Data atual  : 09/09/2021
Var
   // Seção de Declarações das variáveis
   c1,c:inteiro
   r:real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para c de 50 ate 1 passo -1 faca
      Escreval(c)
   fimpara
Fimalgoritmo