Algoritmo "PARA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jaiion Costa dos Santos
// Descrição   : Contador de 0 a 10 usando para
// Autor(a)    : Bruno Costa Prado
// Data atual  : 09/09/2021
Var
   // Seção de Declarações das variáveis
   x,cont:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para cont de 0 ate 10 passo 1 faca
      Escreval(cont)
   fimpara
Fimalgoritmo