Algoritmo "Quadradopara"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jaiion Costa dos Santos 
// Descrição   : Indica o quadrado de um numero
// Autor(a)    : Bruno Costa Prado
// Data atual  : 09/09/2021
Var
// Seção de Declarações das variáveis 
x:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 para x de 15 ate 200 passo 1 faca
 Escreval(x,"² =", x*x)
 fimpara
Fimalgoritmo