   Algoritmo "Repita"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jaison Costa do Santos
// Descrição   : Laço de repetição ate
// Autor(a)    : Bruno Costa Prado
// Data atual  : 08/09/2021
Var
   // Seção de Declarações das variáveis
   cont:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   cont<-0
   repita
      Escreval (cont)
      cont<-cont+1
   ate cont>5
Fimalgoritmo